kind: Secret
apiVersion: v1
metadata:
  name: postgres-secrets
  namespace: sonataflow-infra
  labels: 
    app: kogito
data:
  POSTGRES_USER: {{.Values.postgres.user}}
  POSTGRES_PASSWORD: {{.Values.postgres.pw}}
type: Opaque