apiVersion: v1
data:
  application.properties: |
    kogito.service.url=${kubernetes:services.v1/event-timeout}
    quarkus.log.category."io.smallrye.reactive.messaging".level = DEBUG
    quarkus.log.category."org.kie".level = DEBUG
    quarkus.log.category."io.quarkus.reactivemessaging".level = DEBUG
    quarkus.log.category."io.vertx".level = DEBUG
    quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-db-service.sonataflow-infra.svc.cluster.local:5432/sonataflow
    quarkus.datasource.username=<PG_USER>
    quarkus.datasource.password=<PG_PWD>
    kogito.jobs-service.url=${kubernetes:services.v1/jobs-service-service}

    # Job Service kogito-addons-quarkus-jobs-knative-eventing configuration
    mp.messaging.outgoing.kogito-job-service-job-request-events.connector=quarkus-http
    mp.messaging.outgoing.kogito-job-service-job-request-events.url=http://jobs-service-service.sonataflow-infra.svc.cluster.local/v2/jobs/events
    
    # Data Index configuration
    mp.messaging.outgoing.kogito-processinstances-events.url=http://data-index-service.sonataflow-infra.svc.cluster.local/processes
    mp.messaging.outgoing.kogito-usertaskinstances-events.url=http://data-index-service.sonataflow-infra.svc.cluster.local/tasks
    mp.messaging.outgoing.kogito-variables-events.url=http://data-index-service.sonataflow-infra.svc.cluster.local/variables
    
    # Skip user tasks and variables events sending.
    kogito.events.usertasks.enabled=false
    kogito.events.variables.enabled=false
kind: ConfigMap
metadata:
  labels:
    app: event-timeout
  name: event-timeout-props