kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels: 
      app: postgres-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgres-db
  labels: 
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: dbfiles
          envFrom:
            - secretRef:
                name: postgres-secrets
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/dbfiles
            - name: POSTGRES_DB
              value: sonataflow
            - name: POSTGRES_HOST_AUTH_METHOD
              value: password
            - name: POSTGRES_INITDB_ARGS
              value: "-U postgres"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-db-service
  labels: 
      app: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
